# .pre-commit-config.yaml
# Pre-commit configuration for Black code formatter using system Python

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--check", "src/"]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--check-untyped-defs", "--disable-error-code=import-untyped"]
      - id: flake8-syntax
        name: flake8-syntax
        entry: flake8
        language: system
        types: [python]
        args:
          ["--count", "--select=E9,F63,F7,F82", "--show-source", "--statistics"]
      - id: flake8-line-length
        name: flake8-line-length
        entry: flake8
        language: system
        types: [python]
        args:
          [
            "--count",
            "--exit-zero",
            "--max-complexity=10",
            "--max-line-length=127",
            "--statistics",
          ]

      - id: unittest
        name: unittest
        entry: python3 -m unittest discover -s tests
        language: system
        types: [python]
