# .pre-commit-config.yaml
# Pre-commit configuration for Black code formatter using system Python

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["src/"]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["src/"]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["src/"]
