site_name: geonodectl — a commandline tool to manage GeoNode objects
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - Home: index.md
  - Getting Started: example.md
  - Commands:
      - Datasets: datasets.md
      - Documents: documents.md
      - Maps: maps.md
      - GeoApps: geoapps.md
      - Users: users.md
      - Groups: groups.md
      - Resources: resources.md
      - Uploads: uploads.md
      - Execution Requests: executionrequest.md
      - Keywords: keywords.md
      - Linked Resources: linked-resources.md
      - Attributes: attributes.md
      - GeoServer Styles: geoserver.md
