name: Build Docs on Release

on:
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build documentation
        run: |
          mkdocs build

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
