name: Create Release on Version Change

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -n1 | awk -F '"' '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest release version
        id: get_latest_release
        run: |
          LATEST=$(gh release list --limit 1 | awk '{print $1}')
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release if version changed
        if: steps.get_version.outputs.version != steps.get_latest_release.outputs.latest
        run: |
          gh release create "${{ steps.get_version.outputs.version }}" --title "Release ${{ steps.get_version.outputs.version }}" --notes "Automated release for version ${{ steps.get_version.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
